apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 8080   # Exposing the web server port
      targetPort: 8080
  type: LoadBalancer  # If using a cloud provider; use NodePort if running locally
